using System;
using System.Collections.Generic;
using System.Linq;
using DOL.GS.RealmAbilities;

namespace DOL.GS
{
    /// <summary>
    /// One passive realm ability path for each class generated by the autonomous
    /// population. The runtime class list and ability costs remain authoritative.
    /// </summary>
    public static class AutonomousRealmAbilityTraining
    {
        private static readonly Type[] Guard =
            [typeof(DeterminationAbility), typeof(MasteryOfPain), typeof(RADexterityEnhancer), typeof(XToughnessAbility),
                typeof(RAConstitutionEnhancer), typeof(PhysicalDefenceAbility)];
        private static readonly Type[] Melee =
            [typeof(DeterminationAbility), typeof(MasteryOfPain), typeof(XToughnessAbility),
                typeof(RAStrengthEnhancer), typeof(RADexterityEnhancer), typeof(RAConstitutionEnhancer)];
        private static readonly Type[] Mixed =
            [typeof(MasteryOfPain), typeof(WildPowerAbility), typeof(RADexterityEnhancer), typeof(XToughnessAbility),
                typeof(RAConstitutionEnhancer)];
        private static readonly Type[] HealingMelee =
            [typeof(MasteryOfHealingAbility), typeof(MasteryOfPain), typeof(RADexterityEnhancer), typeof(XToughnessAbility),
                typeof(RAConstitutionEnhancer)];
        private static readonly Type[] Healing =
            [typeof(MasteryOfHealingAbility), typeof(WildHealingAbility), typeof(RADexterityEnhancer), typeof(XSerenityAbility),
                typeof(XToughnessAbility), typeof(RAConstitutionEnhancer)];
        private static readonly Type[] SongMelee =
            [typeof(MasteryOfPain), typeof(XToughnessAbility), typeof(RAConstitutionEnhancer),
                typeof(RAStrengthEnhancer), typeof(RADexterityEnhancer)];
        private static readonly Type[] ControlCaster =
            [typeof(WildPowerAbility), typeof(RADexterityEnhancer), typeof(MasteryOfMageryAbility),
                typeof(XSerenityAbility), typeof(RAAcuityEnhancer), typeof(XToughnessAbility)];
        private static readonly Type[] DamageCaster =
            [typeof(WildPowerAbility), typeof(MasteryOfMageryAbility), typeof(RADexterityEnhancer),
                typeof(RAAcuityEnhancer), typeof(XToughnessAbility)];
        private static readonly Type[] PetCaster =
            [typeof(WildPowerAbility), typeof(MasteryOfMageryAbility), typeof(RADexterityEnhancer), typeof(XSerenityAbility),
                typeof(XToughnessAbility)];
        private static readonly Type[] Assassin =
            [typeof(MasteryOfPain), typeof(PhysicalDefenceAbility), typeof(XToughnessAbility),
                typeof(RAStrengthEnhancer), typeof(RADexterityEnhancer)];
        private static readonly Type[] Archer =
            [typeof(RADexterityEnhancer), typeof(PhysicalDefenceAbility), typeof(XToughnessAbility),
                typeof(RAConstitutionEnhancer)];

        private static readonly IReadOnlyDictionary<eCharacterClass, Type[]> Plans =
            new Dictionary<eCharacterClass, Type[]>
            {
                [eCharacterClass.Paladin] = Guard, [eCharacterClass.Armsman] = Guard,
                [eCharacterClass.Warrior] = Guard, [eCharacterClass.Hero] = Guard,
                [eCharacterClass.Mercenary] = Melee, [eCharacterClass.Reaver] = Melee,
                [eCharacterClass.Blademaster] = Melee, [eCharacterClass.Champion] = Melee,
                [eCharacterClass.Berserker] = Melee, [eCharacterClass.Savage] = Melee,
                [eCharacterClass.Thane] = Mixed, [eCharacterClass.Valewalker] = Mixed,
                [eCharacterClass.Friar] = HealingMelee, [eCharacterClass.Warden] = HealingMelee,
                [eCharacterClass.Cleric] = Healing, [eCharacterClass.Healer] = Healing,
                [eCharacterClass.Druid] = Healing, [eCharacterClass.Bard] = Healing,
                [eCharacterClass.Shaman] = Healing,
                [eCharacterClass.Minstrel] = SongMelee, [eCharacterClass.Skald] = SongMelee,
                [eCharacterClass.Sorcerer] = ControlCaster, [eCharacterClass.Mentalist] = ControlCaster,
                [eCharacterClass.Wizard] = DamageCaster, [eCharacterClass.Eldritch] = DamageCaster,
                [eCharacterClass.Runemaster] = DamageCaster,
                [eCharacterClass.Theurgist] = PetCaster, [eCharacterClass.Cabalist] = PetCaster,
                [eCharacterClass.Necromancer] = PetCaster, [eCharacterClass.Enchanter] = PetCaster,
                [eCharacterClass.Spiritmaster] = PetCaster, [eCharacterClass.Bonedancer] = PetCaster,
                [eCharacterClass.Animist] = PetCaster,
                [eCharacterClass.Infiltrator] = Assassin, [eCharacterClass.Shadowblade] = Assassin,
                [eCharacterClass.Nightshade] = Assassin,
                [eCharacterClass.Scout] = Archer, [eCharacterClass.Ranger] = Archer,
                [eCharacterClass.Hunter] = Archer,
            };

        // The Atlas old-frontier Serenity and Toughness handlers do not derive
        // from their normal-mode counterparts. Match only these audited aliases.
        private static bool Matches(RealmAbility ability, Type plannedType) =>
            plannedType.IsInstanceOfType(ability) ||
            plannedType == typeof(XSerenityAbility) && ability is AtlasOF_SerenityAbility ||
            plannedType == typeof(XToughnessAbility) && ability is AtlasOF_ToughnessAbility;

        private static IReadOnlyList<RealmAbility> PlanAbilities(int classId)
        {
            if (!Plans.TryGetValue((eCharacterClass)classId, out Type[] plan))
                return [];
            List<RealmAbility> available = SkillBase.GetClassRealmAbilities(classId)
                .Where(ability => ability is not TimedRealmAbility && ability.MaxLevel > 0)
                .ToList();
            return plan.Select(type => available.FirstOrDefault(ability => Matches(ability, type)))
                .Where(ability => ability != null).DistinctBy(ability => ability.KeyName).ToList();
        }

        public static bool TryRead(string serialized, int classId, int pointPool,
            out Dictionary<string, int> allocations)
        {
            allocations = new Dictionary<string, int>(StringComparer.Ordinal);
            if (string.IsNullOrEmpty(serialized))
                return true;
            IReadOnlyDictionary<string, RealmAbility> legal = PlanAbilities(classId)
                .ToDictionary(ability => ability.KeyName, StringComparer.Ordinal);
            int spent = 0;
            foreach (string entry in serialized.Split(';', StringSplitOptions.RemoveEmptyEntries))
            {
                if (!entry.StartsWith("ra|", StringComparison.Ordinal))
                    continue;
                string[] fields = entry.Split('|');
                if (fields.Length != 3 || !legal.TryGetValue(fields[1], out RealmAbility ability) ||
                    !int.TryParse(fields[2], out int rank) || rank < 1 || rank > ability.MaxLevel ||
                    allocations.ContainsKey(fields[1]))
                    return false;
                for (int current = 0; current < rank; current++)
                {
                    int cost = ability.CostForUpgrade(current);
                    if (cost < 0 || cost > pointPool - spent)
                        return false;
                    spent += cost;
                }
                allocations.Add(fields[1], rank);
            }
            return true;
        }

        public static string Serialize(byte trainedLevel, IReadOnlyDictionary<string, int> allocations) =>
            "trained-level|" + trainedLevel + string.Concat(allocations.OrderBy(pair => pair.Key, StringComparer.Ordinal)
                .Select(pair => ";ra|" + pair.Key + "|" + pair.Value));

        public static string UpdateTrainingLevelPreservingInvalidAllocations(string serialized, byte trainedLevel)
        {
            string header = "trained-level|" + trainedLevel;
            if (string.IsNullOrEmpty(serialized))
                return header;
            if (serialized.StartsWith("trained-level|", StringComparison.Ordinal) ||
                serialized.StartsWith("generated-level|", StringComparison.Ordinal))
            {
                int separator = serialized.IndexOf(';');
                return header + (separator >= 0 ? serialized[separator..] : string.Empty);
            }
            return header + ";" + serialized;
        }

        public static bool Advance(GameBot bot, IDictionary<string, int> allocations)
        {
            IReadOnlyList<RealmAbility> abilities = PlanAbilities(bot.ClassId);
            if (abilities.Count == 0)
                return false;
            int pool = CompanionRealmAbilityTraining.PointPool(bot.Level, bot.AutonomousRealmPoints);
            int spent = abilities.Sum(ability => allocations.TryGetValue(ability.KeyName, out int rank)
                ? Enumerable.Range(0, rank).Sum(ability.CostForUpgrade) : 0);
            int remaining = Math.Max(0, pool - spent);
            bool changed = false;
            // A fixed purchase sequence makes the eventual build independent of
            // whether RP arrives in small kills or one larger award.
            int maxRank = abilities.Max(ability => ability.MaxLevel);
            for (int stage = 1; stage <= maxRank; stage++)
            {
                foreach (RealmAbility ability in abilities)
                {
                    int target = stage;
                    int rank = allocations.TryGetValue(ability.KeyName, out int current) ? current : 0;
                    if (rank >= target || rank >= ability.MaxLevel)
                        continue;
                    int cost = ability.CostForUpgrade(rank);
                    if (cost < 0 || cost > remaining)
                        return changed;
                    ability.Level = rank + 1;
                    bot.AddAbility(ability, false);
                    allocations[ability.KeyName] = rank + 1;
                    remaining -= cost;
                    changed = true;
                }
            }
            return changed;
        }

        public static void Restore(GameBot bot, IReadOnlyDictionary<string, int> allocations)
        {
            foreach (RealmAbility ability in PlanAbilities(bot.ClassId))
            {
                if (!allocations.TryGetValue(ability.KeyName, out int rank))
                    continue;
                ability.Level = rank;
                bot.AddAbility(ability, false);
            }
        }
    }
}
